[supervisord]
nodaemon=true

[program:tgBotV5]
command=python ./tgBotV5.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/tgBotV5.out.log
stderr_logfile=/app/logs/tgBotV5.err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
